Added README.md
trebleshot/trebleshot.github.io pull request #16
Opened 2020-11-29 14:05 UTC by Nivedita967

Adding a README will help people interested in this repository to understand your project (easily and smoothly).

2020-11-30 16:03 UTC, velitasali requested changes
Thanks for working on this. Other than the formatting and small coherence issues, this is mergeable.

2020-11-30 16:03 UTC, velitasali commented on README.md
> +Download it today!<br>
Using two lines, in other words `\n\n`, will have the same effect as using <br>

2020-11-30 16:03 UTC, velitasali commented on README.md
> +1> Resume Transfers-<br>
There is a better formatting option for numbered bullet points:

```markdown
1. First
2. Second
3. Third
```

2020-11-30 19:31 UTC, velitasali commented
Alright, this looks good for a start. Other people can improve upon it. 

Thanks :+1:

2020-11-30 19:31 UTC, merged

2020-12-01 05:27 UTC, Nivedita967 commented
Sure.